---
authors:
  - Larry Smith Jr. <mrlesmithjr@gmail.com>
build_ignore:
  - venv/**
  - .gitignore
dependencies: {}
description: Ansible collection of system related roles
documentation: https://github.com/mrlesmithjr/ansible-collection-system/docs
homepage: https://github.com/mrlesmithjr/ansible-collection-system
issues: https://github.com/mrlesmithjr/ansible-collection-system/issues
license_file: LICENSE.md
name: system
namespace: mrlesmithjr
readme: README.md
repository: https://github.com/mrlesmithjr/ansible-collection-system
tags:
  - system
version: 0.2.0
