---
- name: Converge
  hosts: all
  vars:
    apt_sources_enable_backports: false
    cloud_init_clean: true
    cloud_init_config: true
    configure_postfix: true
  tasks:
    - name: Test apt_sources Role
      import_role:
        name: apt_sources
      when:
        - lookup('env', 'COLLECTION_ROLE') == "apt_sources"
        - ansible_os_family == "Debian"

    - name: Test base Role
      import_role:
        name: base
      when: lookup('env', 'COLLECTION_ROLE') == "base"

    - name: Test bootstrap_python Role
      import_role:
        name: bootstrap_python
      when: lookup('env', 'COLLECTION_ROLE') == "bootstrap_python"

    - name: Test chrony Role
      import_role:
        name: chrony
      when: lookup('env', 'COLLECTION_ROLE') == "chrony"

    - name: Test cloud_init Role
      import_role:
        name: cloud_init
      when: lookup('env', 'COLLECTION_ROLE') == "cloud_init"

    - name: Test motd Role
      import_role:
        name: motd
      when: lookup('env', 'COLLECTION_ROLE') == "motd"

    - name: Test ntp Role
      import_role:
        name: ntp
      when: lookup('env', 'COLLECTION_ROLE') == "ntp"

    - name: Test postfix Role
      import_role:
        name: postfix
      when: lookup('env', 'COLLECTION_ROLE') == "postfix"

    - name: Test rsyslog Role
      import_role:
        name: rsyslog
      when: lookup('env', 'COLLECTION_ROLE') == "rsyslog"

    - name: Test sshd Role
      import_role:
        name: sshd
      when: lookup('env', 'COLLECTION_ROLE') == "sshd"
