---
- name: Converge
  hosts: all
  vars:
    apt_sources_enable_backports: false
    configure_postfix: true
  tasks:
    - name: Test apt_sources Role
      import_role:
        name: apt_sources
      when:
        - lookup('env', 'COLLECTION_ROLE') == "apt_sources"
        - ansible_os_family == "Debian"

    - name: Test bootstrap_python Role
      import_role:
        name: bootstrap_python
      when: lookup('env', 'COLLECTION_ROLE') == "bootstrap_python"

    - name: Test chrony Role
      import_role:
        name: chrony
      when: lookup('env', 'COLLECTION_ROLE') == "chrony"

    - name: Test motd Role
      import_role:
        name: motd
      when: lookup('env', 'COLLECTION_ROLE') == "motd"

    - name: Test ntp Role
      import_role:
        name: ntp
      when: lookup('env', 'COLLECTION_ROLE') == "ntp"

    - name: Test postfix Role
      import_role:
        name: postfix
      when: lookup('env', 'COLLECTION_ROLE') == "postfix"
