name: mrlesmithjr.system.ntp
on:
  push:
    paths:
      - ".github/workflows/ntp.yml"
      - "molecule/**"
      - "requirements-dev.txt"
      - "requirements.txt"
      - "roles/ntp"
  pull_request:
    paths:
      - ".github/workflows/ntp.yml"
      - "molecule/**"
      - "requirements-dev.txt"
      - "requirements.txt"
      - "roles/ntp"
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          - centos7
          # - centos8
          # - debian8
          - debian9
          - debian10
          - fedora
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
        collection_role:
          - ntp
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt requirements-dev.txt
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          export COLLECTION_ROLE="${{ matrix.collection_role }}"
          molecule test --scenario-name ${{ matrix.molecule_distro }}
